### PR TITLE
Scope usage of private libextobjc headers

### PR DESCRIPTION
**Pull request by neonichu**
This makes Mantle still compile if both its own private copy and the original libextobjc headers are available in its header search paths.

See CocoaPods/CocoaPods#4166

### CODE REVIEW

**Comment by robb** [comment]
LGTM

**Comment by RonanLB** [comment]
I would be very grateful if that change would make it to version 1.5.x because I am having the very same issue and we're not ready yet to move to Mantle 2.x

**Comment by RonanLB** [comment]
I have made a small podspec on a project that depends on Mantle 1.5.5 and libextobjc
running pod lib lint works with xcode 6.0 console tools and cocoapods 0.37.1

but does not work with xcode 7.0.1 console tools and cocoapods 0.39.0.beta.5

it produces those errors:
 - ERROR | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel+NSCoding.m:74:3: error: unknown type name 'mtl_propertyAttributes'; did you mean 'ext_propertyAttributes'?
   - NOTE  | [podTest/Mantle] xcodebuild:  Headers/Private/libextobjc/EXTRuntimeExtensions.h:158:3: note: 'ext_propertyAttributes' declared here
   - WARN  | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel+NSCoding.m:74:40: warning: implicit declaration of function 'mtl_copyPropertyAttributes' is invalid in C99 [-Wimplicit-function-declaration]
   - WARN  | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel+NSCoding.m:74:27: warning: incompatible integer to pointer conversion initializing 'ext_propertyAttributes *' with an expression of type 'int' [-Wint-conversion]
   - ERROR | [iOS] xcodebuild:  Mantle/Mantle/MTLModel+NSCoding.m:101:3: error: unknown type name 'mtl_propertyAttributes'; did you mean 'ext_propertyAttributes'?
   - WARN  | [iOS] xcodebuild:  Mantle/Mantle/MTLModel+NSCoding.m:101:27: warning: incompatible integer to pointer conversion initializing 'ext_propertyAttributes *' with an expression of type 'int' [-Wint-conversion]
   - ERROR | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel.m:142:3: error: unknown type name 'mtl_propertyAttributes'; did you mean 'ext_propertyAttributes'?
   - WARN  | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel.m:142:40: warning: implicit declaration of function 'mtl_copyPropertyAttributes' is invalid in C99 [-Wimplicit-function-declaration]
   - WARN  | [podTest/Mantle] xcodebuild:  Mantle/Mantle/MTLModel.m:142:27: warning: incompatible integer to pointer conversion initializing 'ext_propertyAttributes *' with an expression of type 'int' [-Wint-conversion]

**Comment by mrezk** [comment]
I am having the same issue as @RonanLB. @robb Is there any chance of releasing a Mantle 1.5.6 with this fix?

**Comment by RonanLB** [comment]
I have forked the project and made some changes to rename the conflicting files.
I could make a pull request if you're interested.

cocoapods 0.39.rc1 got released. @mrezk does it produce the same result ?

**Comment by robb** [comment]
A pull request would be appreciated

**Comment by priteshshah1983** [comment]
I'd like this fix as well. +1 for `v1.5.6`

**Comment by RonanLB** [comment]
I've created a branch on my fork:
https://github.com/RonanLB/Mantle/tree/maintenance_1.5.x

@mrezk any chance that we create a maintenance branch on Mantle repo so that I could create a pull request ?

Kind regards
Ronan

**Comment by robb** [comment]
There you go https://github.com/Mantle/Mantle/tree/1.x-maintenance

**Comment by RonanLB** [comment]
pull request has been created, thank you @robb 
https://github.com/Mantle/Mantle/pull/623

**Comment by mrezk** [comment]
@robb @RonanLB thanks!
